spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:carl-db-sharding.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

rocketmq:
  producer:
    nameSrv: 192.168.237.138:9876
    groupName: ${spring.application.name}
    retryCount: 3
    sendTimeOut: 3000

  consumer:
    nameSrv: 192.168.237.138:9876
    groupName: ${spring.application.name}